version: '3.8'

services:
  app:
    build: .
    container_name: randomwords-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/randomwords
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: randomwords-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vocabulary_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
